const CONFIGURED_RULE_TYPES = {
  KYC: 0,
  KYC_AGE: 1,
  KYC_COUNTRY: 2,
  KYC_COUNTRY_AGE: 3,
  AML: 4,
  AML_KYC: 5,
  AML_OPTIONAL_KYC: 6,
};

const DEFAULT_RULE_TYPE_VALUES = {
  [CONFIGURED_RULE_TYPES.KYC]: '777',
  [CONFIGURED_RULE_TYPES.KYC_AGE]: '231',
  [CONFIGURED_RULE_TYPES.KYC_COUNTRY]: '131',
  [CONFIGURED_RULE_TYPES.KYC_COUNTRY_AGE]: '331',
  [CONFIGURED_RULE_TYPES.AML]: '431050',
  [CONFIGURED_RULE_TYPES.AML_KYC]: '731090',
  [CONFIGURED_RULE_TYPES.AML_OPTIONAL_KYC]: '631050090',
};

const RULE_TYPE_OPTIONS = [
  {
    label: 'KYC',
    value: CONFIGURED_RULE_TYPES.KYC,
  },
  {
    label: 'KYC + AGE',
    value: CONFIGURED_RULE_TYPES.KYC_AGE,
  },
  {
    label: 'KYC + COUNTRY',
    value: CONFIGURED_RULE_TYPES.KYC_COUNTRY,
  },
  {
    label: 'KYC + COUNTRY + AGE',
    value: CONFIGURED_RULE_TYPES.KYC_COUNTRY_AGE,
  },
  {
    label: 'AML',
    value: CONFIGURED_RULE_TYPES.AML,
  },
  {
    label: 'AML + KYC',
    value: CONFIGURED_RULE_TYPES.AML_KYC,
  },
  {
    label: 'AML + OPTIONAL KYC (Type 2)',
    value: CONFIGURED_RULE_TYPES.AML_OPTIONAL_KYC,
  },
];

const DEFAULT_RULE_TYPE = CONFIGURED_RULE_TYPES.KYC;

export {
  CONFIGURED_RULE_TYPES,
  DEFAULT_RULE_TYPE_VALUES,
  RULE_TYPE_OPTIONS,
  DEFAULT_RULE_TYPE,
};
